opentelemetry-collector:
  config:
    receivers:
      otlp:
        protocols:
          grpc:
          http:
            cors:
              allowed_origins:
                - "http://*"
                - "https://*"

    exporters:
      otlp:
        endpoint: '{{ include "otel-demo.name" . }}-jaeger:4317'
        tls:
          insecure: true
      prometheus:
        endpoint: '0.0.0.0:9464'
      instana:
        endpoint: https://serverless-red-saas.instana.io
        agent_key: XXXXXXXXXXX

    processors:
      spanmetrics:
        metrics_exporter: prometheus

    service:
      pipelines:
        traces:
          processors: [memory_limiter, spanmetrics, batch]
          exporters: [otlp, logging, instana]
        metrics:
          exporters: [prometheus, logging]
